version: '3'

services:
  analytics:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - analytics_data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/analytics.db
      - IP_HASH_SALT=UJSgmCck1xrg4WJ5UboQzPEekzoOhtAIlkbrDoCsCpc=
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=secure_dashboard_password_here
      - RATE_LIMIT=100

volumes:
  analytics_data:
    driver: local
